### ISSUE TITLE
Unable to build on my windows system 

### ISSUE THREAD

**Issue by hackertron** [soramimi/qSIP#1]
hello i tried to build QSIP on my windows system . I am using Qt 5.9 on windows 10 . 

when i build it i get following error 

:-1: error: LNK1104: cannot open file 'baresipd.lib'

**Comment by soramimi** [comment]
There are 9 project files.

- baresip.pro
- g722.pro
- gsm.pro
- portaudio.pro
- qSIP.pro
- re.pro
- rem.pro
- speex.pro
- webrtc.pro

Open everything with Qt Creator except qSIP.pro
Run "Rebuild all"

Check that library files was created.

- _build\baresipd.lib
- _build\g722d.lib
- _build\gsmd.lib
- _build\portaudiod.lib
- _build\red.lib
- _build\remd.lib
- _build\speexd.lib
- _build\webrtcd.lib

Run "Close all Projects and Editors"

Finally, Open qSIP.pro and build it.

**Comment by hackertron** [comment]
not able to build baresip project . i am getting erros .

**Comment by soramimi** [comment]
Yellow exclamations are warnings, so you can ignore it.
Red is error, please scroll messages, and show me error messages.

**Comment by hackertron** [comment]
![er1](https://user-images.githubusercontent.com/7667514/31503754-1aec6cec-af8e-11e7-8813-76ac3542a6fd.PNG)
![er2](https://user-images.githubusercontent.com/7667514/31503756-1d9691a2-af8e-11e7-814a-a5070b8f8fd0.PNG)

**Comment by soramimi** [comment]
I guess you are probably using Qt 64-bit edition.
but qSIP is not supported 64-bit edition.
Qt for Windows is provided with 32-bit and 64-bit edition.
Please try to use 32-bit compiler and Qt library.

**Comment by hackertron** [comment]
Okay i will try it :+1:  . Thanks !! :)

**Comment by hackertron** [comment]
Can it be build on linux system too ?

**Comment by soramimi** [comment]
Now, I committed a small fix.

Please try the following.

1. git pull
2. open qSIP.pro with Qt Creator
3. [Edit] -> [Run qmake]
4. build

**Comment by hackertron** [comment]
Hey can you send me the compiled/build version of Qsip ? . I am still having issues with building it

**Comment by soramimi** [comment]
https://files.soramimi.jp/qsip/
First, please install Visual C++ 2013 Redistributable Package (vcredist_x86.exe).

By the way, I have not used MinGW compiler.
My favorite development environment is MSVC 2013 and Qt 5.7.1
If you want to build by yourself, I recommend that you get MSVC 2013 for Windows Desktop.
Of course, Express Edition is fine. It is for free.

**Comment by hackertron** [comment]
Thanks for the upload . The thing is i built the source on an old system i have in which 32-bit windows was installed with Mingw . 

My main environment is VS 2015 with Qt 5.9.0 . 

By the way why 32-bit not on 64 ?

**Comment by soramimi** [comment]
The code that you showed me the other day contains the keyword '__asm'. This means that an inline assembler is used. However, the inline assembler can not be used with the 64-bit compiler.

Compiler and libraries must use 32 bit edition. However, OS can use 64-bit Windows.

**Comment by hackertron** [comment]
Are you on any forum / social site , would love to connect with you and collaborate on a project :D .

**Comment by soramimi** [comment]
I use only Japanese social sites.
for example, the following sites.
- Qt users group JP
- stackoverflow JP
- Qiita
- Twitter

Usually I speak only Japanese.
Please send issue when you have something requests.
